#!/usr/bin/env python3
"""
anatomy-link/scripts/link.py

Inserts or updates a single marked, idempotent block in agent-instruction
files (AGENTS.md, CLAUDE.md, ...) that points coding agents at an existing
`anatomy` skill output (docs/anatomy/ by default), so a fresh session finds
the architecture docs instead of re-deriving them from source.

Only the text between <!-- anatomy:start --> and <!-- anatomy:end --> is
ever touched. Everything else in the target file is left byte-for-byte
alone. Re-running with nothing changed produces no diff.

Usage:
    python3 link.py <repo_root> [--anatomy-root docs/anatomy]
                                 [--targets AGENTS.md CLAUDE.md]
                                 [--create]
                                 [--check]

Exit codes:
    0  success (including "nothing to do, already up to date")
    1  no anatomy output found at --anatomy-root (nothing to link to)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MARK_START = "<!-- anatomy:start -->"
MARK_END = "<!-- anatomy:end -->"

DEFAULT_TARGETS = ["AGENTS.md", "CLAUDE.md"]

BLOCK_PATTERN = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.DOTALL)


def load_anatomy_state(anatomy_root: Path):
    """Read what we need from an existing anatomy output: which optional
    files exist, and a human-readable freshness note from the manifest.
    Returns None if anatomy_root doesn't look like a real anatomy output."""
    if not (anatomy_root / "index.md").exists():
        return None

    freshness = "date/commit unknown -- no _manifest.json found"
    manifest_path = anatomy_root / "_manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            commit = manifest.get("source_commit")
            freshness = f"as of commit `{commit[:12]}`" if commit else "commit unknown (not a git repo at trace time)"
        except (json.JSONDecodeError, OSError):
            pass

    return {
        "has_data_model": (anatomy_root / "data-model.md").exists(),
        "has_deployment": (anatomy_root / "deployment.md").exists(),
        "has_html_diagram": (anatomy_root / "system-diagram.html").exists(),
        "freshness": freshness,
    }


def build_block(anatomy_root_rel: str, state: dict) -> str:
    r = anatomy_root_rel.rstrip("/")
    lines = [
        MARK_START,
        "## Architecture docs (generated by the `anatomy` skill)",
        "",
        f"This repo has traced architecture docs under `{r}/`. **Read "
        f"`{r}/index.md` first** before exploring the codebase from "
        "scratch -- it has the module map, tech stack, entry points, and "
        "links to everything else below.",
        "",
        f"- `{r}/index.md` -- start here: overview, module table, entry "
        "points, codebase health signals",
        f"- `{r}/entry-points.md` -- every HTTP route / CLI command / "
        "queue consumer / cron job, in one place",
        f"- `{r}/system-diagram.md` -- module & dependency graph (Mermaid)",
    ]
    if state["has_html_diagram"]:
        lines.append(
            f"- `{r}/system-diagram.html` -- same diagram, interactive -- "
            "open directly in a browser"
        )
    lines.append(
        f"- `{r}/modules/<slug>.md` -- one file per module: "
        "responsibilities, public interface, dependencies"
    )
    if state["has_data_model"]:
        lines.append(f"- `{r}/data-model.md` -- ERD-style data model")
    if state["has_deployment"]:
        lines.append(f"- `{r}/deployment.md` -- deployment/infra topology")

    lines += [
        "",
        f"Traced {state['freshness']}. If this looks stale against recent "
        "changes, re-run the `anatomy` skill to refresh it before trusting "
        "it -- don't re-derive the architecture from source by hand when "
        "these docs already exist.",
        MARK_END,
    ]
    return "\n".join(lines)


def upsert_block(content: str, block: str) -> tuple[str, bool]:
    """Insert `block` into `content` if absent, or replace the existing
    marked region if present. Returns (new_content, changed)."""
    match = BLOCK_PATTERN.search(content)

    if match:
        if match.group(0) == block:
            return content, False
        return content[: match.start()] + block + content[match.end() :], True

    # No existing block: insert right after the file's first top-level
    # heading (and any blank line after it), or at the very top if there
    # isn't one.
    lines = content.split("\n")
    insert_idx = 0
    if lines and lines[0].strip().startswith("# "):
        insert_idx = 1
        while insert_idx < len(lines) and lines[insert_idx].strip() == "":
            insert_idx += 1

    before = lines[:insert_idx]
    after = lines[insert_idx:]

    new_lines = before + ([""] if before else []) + block.split("\n") + [""] + after
    new_content = "\n".join(new_lines)
    new_content = re.sub(r"\n{3,}", "\n\n", new_content)
    if not new_content.endswith("\n"):
        new_content += "\n"
    return new_content, True


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("repo_root", type=Path, help="Repository root")
    parser.add_argument(
        "--anatomy-root",
        default="docs/anatomy",
        help="Path (relative to repo_root) to the anatomy output. Default: docs/anatomy",
    )
    parser.add_argument(
        "--targets",
        nargs="+",
        default=DEFAULT_TARGETS,
        help="Files (relative to repo_root) to link into. Default: AGENTS.md CLAUDE.md",
    )
    parser.add_argument(
        "--create",
        action="store_true",
        help="Create target files that don't exist yet, instead of skipping them.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report what would change without writing anything.",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    anatomy_root = (repo_root / args.anatomy_root).resolve()

    state = load_anatomy_state(anatomy_root)
    if state is None:
        print(
            f"error: no anatomy output found at {anatomy_root} "
            f"(expected {anatomy_root}/index.md to exist). "
            "Run the `anatomy` skill first, or pass --anatomy-root if it "
            "was traced somewhere else.",
            file=sys.stderr,
        )
        return 1

    anatomy_root_rel = str(Path(args.anatomy_root))
    block = build_block(anatomy_root_rel, state)

    any_target_existed = False
    results = []
    for name in args.targets:
        target = repo_root / name
        if target.exists():
            any_target_existed = True
            original = target.read_text(encoding="utf-8")
            new_content, changed = upsert_block(original, block)
            if changed and not args.check:
                target.write_text(new_content, encoding="utf-8")
            results.append((name, "updated" if changed else "unchanged (already up to date)"))
        elif args.create:
            title = Path(name).stem
            base = f"# {title}\n"
            new_content, _ = upsert_block(base, block)
            if not args.check:
                target.write_text(new_content, encoding="utf-8")
            results.append((name, "created"))
        else:
            results.append((name, "skipped (does not exist -- pass --create to create it)"))

    if not any_target_existed and not args.create:
        print(
            "warning: none of the target files exist yet. Pass --create to "
            "create them, or point --targets at the files this project "
            "actually uses.",
            file=sys.stderr,
        )

    for name, status in results:
        print(f"{name}: {status}")
    if args.check:
        print("\n(--check: no files were written)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
