#!/usr/bin/env python3
"""Insert or update an idempotent anatomy pointer block in agent files."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MARK_START = "<!-- anatomy:start -->"
MARK_END = "<!-- anatomy:end -->"
DEFAULT_TARGETS = ["AGENTS.md", "CLAUDE.md"]
BLOCK_PATTERN = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.DOTALL)


def load_anatomy_state(anatomy_root: Path):
    """Return optional-output and freshness metadata, or None if no trace exists."""
    if not (anatomy_root / "index.md").is_file():
        return None

    freshness = "date/commit unknown -- no _manifest.json found"
    manifest_path = anatomy_root / "_manifest.json"
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            commit = manifest.get("source_commit")
            generated = manifest.get("generated_at")
            if commit:
                freshness = "as of commit `%s`" % str(commit)[:12]
            elif generated:
                freshness = "as of %s (commit unknown)" % generated
            else:
                freshness = "commit unknown (not a git repo at trace time)"
        except (json.JSONDecodeError, OSError, TypeError):
            freshness = "freshness unknown -- _manifest.json is unreadable"

    return {
        "has_data_model": (anatomy_root / "data-model.md").is_file(),
        "has_deployment": (anatomy_root / "deployment.md").is_file(),
        "has_html_diagram": (anatomy_root / "system-diagram.html").is_file(),
        "freshness": freshness,
    }


def build_block(anatomy_root_rel: str, state: dict) -> str:
    r = anatomy_root_rel.rstrip("/")
    lines = [
        MARK_START,
        "## Architecture docs (generated by the `anatomy` skill)",
        "",
        "This repo has traced architecture docs under `%s/`. **Read `%s/index.md` "
        "first** before exploring the codebase from scratch -- it has the module "
        "map, tech stack, entry points, and links to the other outputs." % (r, r),
        "",
        "- `%s/index.md` -- start here: overview, module table, entry points, "
        "codebase health signals" % r,
        "- `%s/entry-points.md` -- confirmed HTTP routes / CLI commands / queue "
        "consumers / cron jobs; explicit grouped coverage is disclosed" % r,
        "- `%s/system-diagram.md` -- module and dependency graph (Mermaid)" % r,
    ]
    if state["has_html_diagram"]:
        lines.append(
            "- `%s/system-diagram.html` -- the same canonical diagram data, "
            "interactive in a browser" % r
        )
    lines.append(
        "- `%s/modules/<slug>.md` -- one file per module: responsibilities, "
        "public interface, and dependencies" % r
    )
    if state["has_data_model"]:
        lines.append("- `%s/data-model.md` -- ERD-style data model" % r)
    if state["has_deployment"]:
        lines.append("- `%s/deployment.md` -- deployment/infra topology" % r)

    lines.extend([
        "",
        "Traced %s. If this looks stale against recent changes, run the "
        "`anatomy-gate` freshness check or refresh it with `anatomy` before "
        "trusting it; do not silently treat generated docs as current." % state["freshness"],
        MARK_END,
    ])
    return "\n".join(lines)


def upsert_block(content: str, block: str):
    match = BLOCK_PATTERN.search(content)
    if match:
        if match.group(0) == block:
            return content, False
        return content[:match.start()] + block + content[match.end():], True

    lines = content.split("\n")
    insert_idx = 0
    if lines and lines[0].strip().startswith("# "):
        insert_idx = 1
        while insert_idx < len(lines) and not lines[insert_idx].strip():
            insert_idx += 1
    before, after = lines[:insert_idx], lines[insert_idx:]
    new_lines = before + ([""] if before else []) + block.split("\n") + [""] + after
    result = "\n".join(new_lines)
    result = re.sub(r"\n{3,}", "\n\n", result)
    if not result.endswith("\n"):
        result += "\n"
    return result, True


def safe_relative_target(repo_root: Path, name: str) -> Path:
    rel = Path(name)
    if rel.is_absolute() or ".." in rel.parts:
        raise ValueError("unsafe target path: %s" % name)
    target = (repo_root / rel).resolve()
    target.relative_to(repo_root)
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo_root", type=Path)
    parser.add_argument("--anatomy-root", default="docs/anatomy")
    parser.add_argument("--targets", nargs="+", default=DEFAULT_TARGETS)
    parser.add_argument("--create", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    try:
        anatomy_root = safe_relative_target(repo_root, args.anatomy_root)
    except ValueError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2

    state = load_anatomy_state(anatomy_root)
    if state is None:
        print(
            "error: no anatomy output found at %s (expected index.md). "
            "Run `anatomy` first or pass --anatomy-root." % anatomy_root,
            file=sys.stderr,
        )
        return 1

    block = build_block(str(Path(args.anatomy_root)), state)
    results = []
    any_target_existed = False
    for name in args.targets:
        try:
            target = safe_relative_target(repo_root, name)
        except ValueError as exc:
            print("error: %s" % exc, file=sys.stderr)
            return 2
        if target.exists():
            if not target.is_file():
                print("error: target is not a file: %s" % target, file=sys.stderr)
                return 2
            any_target_existed = True
            try:
                original = target.read_text(encoding="utf-8")
            except OSError as exc:
                print("error: could not read %s: %s" % (target, exc), file=sys.stderr)
                return 2
            new_content, changed = upsert_block(original, block)
            if changed and not args.check:
                target.write_text(new_content, encoding="utf-8")
            results.append((name, "would update" if changed and args.check else "updated" if changed else "unchanged"))
        elif args.create:
            base = "# %s\n" % Path(name).stem
            new_content, _ = upsert_block(base, block)
            if not args.check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(new_content, encoding="utf-8")
            results.append((name, "would create" if args.check else "created"))
        else:
            results.append((name, "skipped (missing; pass --create to create)"))

    if not any_target_existed and not args.create:
        print("warning: none of the target files exist", file=sys.stderr)
    for name, status in results:
        print("%s: %s" % (name, status))
    if args.check:
        print("\n(--check: no files were written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
