#!/usr/bin/env python3
"""Recompute internal `Used by` bullets by transposing all `Depends on` edges.

This is intentionally a Markdown-preserving patcher, not a document renderer:
it only replaces internal module-reference bullets inside `## Used by`, while
preserving external bullets, comments/prose, later sections, and the trace
coverage footer byte-for-byte.

Usage:
    python3 sync_reverse_edges.py <output_root> [--check | --write]
"""
import argparse
import json
import re
import sys
from pathlib import Path

HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$")
DEPENDS_RE = re.compile(r"^#{1,6}\s+Depends on\s*$", re.IGNORECASE)
USED_BY_RE = re.compile(r"^#{1,6}\s+Used by\s*$", re.IGNORECASE)
INTERNAL_BULLET_RE = re.compile(r"^(\s*)-\s+\*\*`([^`]+)`\*\*\s*(.*)$")
HORIZONTAL_RULE_RE = re.compile(r"^\s*(?:---+|___+|\*\*\*+)\s*$")


def section_bounds(lines, heading_re):
    start = None
    for index, line in enumerate(lines):
        if heading_re.match(line):
            start = index
            break
    if start is None:
        return None
    end = len(lines)
    for index in range(start + 1, len(lines)):
        if HEADING_RE.match(lines[index]) or HORIZONTAL_RULE_RE.match(lines[index]):
            end = index
            break
    return start, end


def extract_depends_bullets(text):
    lines = text.splitlines()
    bounds = section_bounds(lines, DEPENDS_RE)
    result = []
    if bounds is None:
        return result
    _start, end = bounds
    for line in lines[bounds[0] + 1:end]:
        match = INTERNAL_BULLET_RE.match(line)
        if match:
            result.append({"target": match.group(2), "rest": match.group(3).rstrip()})
    return result


def internal_used_by_bullets(reverse_edges):
    rows = []
    seen = set()
    for source, rest in sorted(reverse_edges, key=lambda item: (item[0], item[1])):
        key = (source, rest.strip())
        if key in seen:
            continue
        seen.add(key)
        suffix = (" " + rest.strip()) if rest.strip() else ""
        rows.append("- **`%s`**%s" % (source, suffix))
    return rows


def find_insert_index(lines):
    depends = section_bounds(lines, DEPENDS_RE)
    if depends is not None:
        return depends[1]
    for index, line in enumerate(lines):
        if HORIZONTAL_RULE_RE.match(line):
            return index
    return len(lines)


def patch_used_by(text, reverse_edges):
    trailing_newline = text.endswith("\n")
    lines = text.splitlines()
    generated = internal_used_by_bullets(reverse_edges)
    bounds = section_bounds(lines, USED_BY_RE)

    if bounds is None:
        insert_at = find_insert_index(lines)
        block = ["## Used by", ""] + (generated or ["None confirmed."]) + [""]
        if insert_at > 0 and lines[insert_at - 1].strip():
            block.insert(0, "")
        new_lines = lines[:insert_at] + block + lines[insert_at:]
    else:
        start, end = bounds
        body = lines[start + 1:end]
        preserved = [line for line in body if not INTERNAL_BULLET_RE.match(line)]

        # Drop only the placeholder generated by an earlier empty transpose.
        preserved = [
            line for line in preserved
            if line.strip().lower() not in {"none confirmed.", "none confirmed", "- none confirmed."}
        ]
        while preserved and not preserved[0].strip():
            preserved.pop(0)
        while preserved and not preserved[-1].strip():
            preserved.pop()

        body_out = [""]
        if generated:
            body_out.extend(generated)
        elif not preserved:
            body_out.append("None confirmed.")
        if preserved:
            if generated:
                body_out.append("")
            body_out.extend(preserved)
        body_out.append("")
        new_lines = lines[:start + 1] + body_out + lines[end:]

    result = "\n".join(new_lines)
    if trailing_newline:
        result += "\n"
    return result


def build_reverse_map(documents):
    slugs = set(documents)
    reverse = {slug: [] for slug in slugs}
    dangling = []
    for source, text in sorted(documents.items()):
        for edge in extract_depends_bullets(text):
            target = edge["target"]
            if target not in slugs:
                dangling.append({"from": source, "to": target})
                continue
            reverse[target].append((source, edge["rest"]))
    return reverse, dangling


def run(output_root, write=False):
    root = Path(output_root).resolve()
    modules_dir = root / "modules"
    if not modules_dir.is_dir():
        raise ValueError("not found: %s" % modules_dir)
    paths = sorted(modules_dir.glob("*.md"))
    documents = {path.stem: path.read_text() for path in paths}
    reverse, dangling = build_reverse_map(documents)
    generated = {}
    changed = []
    for path in paths:
        old = documents[path.stem]
        new = patch_used_by(old, reverse[path.stem])
        if new != old:
            changed.append(path.stem)
            generated[path] = new

    write_blocked = bool(write and dangling)
    if write and not write_blocked:
        originals = {path: documents[path.stem] for path in generated}
        written = []
        try:
            for path, new in generated.items():
                temporary = path.with_name(path.name + ".tmp")
                temporary.write_text(new)
                temporary.replace(path)
                written.append(path)
        except OSError:
            for path in reversed(written):
                temporary = path.with_name(path.name + ".rollback-tmp")
                temporary.write_text(originals[path])
                temporary.replace(path)
            raise
    return {
        "output_root": str(root),
        "mode": "write" if write else "check",
        "modules_checked": sorted(documents),
        "modules_needing_update": changed,
        "dangling_internal_targets": dangling,
        "write_blocked": write_blocked,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("output_root")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="report drift only (default)")
    mode.add_argument("--write", action="store_true", help="patch module docs in place")
    args = parser.parse_args()
    try:
        result = run(args.output_root, write=args.write)
    except (OSError, ValueError) as exc:
        print(json.dumps({"error": str(exc)}, indent=2))
        sys.exit(2)
    print(json.dumps(result, indent=2))
    if result["dangling_internal_targets"] or (not args.write and result["modules_needing_update"]):
        sys.exit(1)


if __name__ == "__main__":
    main()
